CREATE DATABASE STEP3_BOARD_EX;

USE STEP3_BOARD_EX;

CREATE TABLE BOARD(
	NUM 		INT AUTO_INCREMENT PRIMARY KEY,
    WRITER 		VARCHAR(50),
    EMAIL 		VARCHAR(50),
    SUBJECT 	VARCHAR(50),
    PASSWORD 	VARCHAR(20),
    ENROLL_DT 	DATE,
    READ_CNT    INT,
   	CONTENT     VARCHAR(1000)
);

SELECT * FROM BOARD;
